## SETTINGS ##
settings:
  defaultOpenMenu: true # открытие аукциона если нету аргументов
  sell: # Стоимость установки
    min: 1 # мин. кол-во изумрудов
    max: 1000 # макс. кол-во изумрудов
    maxPlace: 3 # макс. выставление предметов
    blockedMaterials: # заблокированные материалы
    - "BEDROCK"
  menu:
    title: "&8&l▪ &2&lАукцион" # наименования
    prevItem:
      name: "&fПредедущая страница"
      type: ARROW
      lore: []
    refreshItem:
      name: "&aОбновить страницу"
      type: knowledge_book
      lore: []
    nextItem:
      name: "&fСледующая страница"
      type: ARROW
      lore: []
    item:
      name: "&fПредмет:&r {name}"
      lore:
      - ""
      - "&f &a▶ &fВладелец: &2{owner}"
      - "&f &a▶ &fСтоимость: &2{price}&a изумруд(а,ов)"
      - "&f &a▶ &fОписания:"
      - "{lore}"
      - ""
      - "&f Нажмите для покупки"
      noLore: " &cОтсуствует" # если отсуствует описания предмета
  
## MESSAGES ##
messages:
  subCommands:
    help:
    - "&r &2&m┎    &r &2&lEmerald&a&lAuction &8↷ &fКоманды:"
    - "&r &2&m┃                                       &r"
    - "&r &2┃ &8⋅ &fВыставление предмета на продажу: &a/{cmd} &2sell &7[&8Цена&7] &7[&8Кол-во&7]"
    - "&r &2┃ &8⋅ &fПерезагрузка конфигруации: &a/{cmd} &2reload"
    - "&r &2&m┃                                       &r"
    - "&r &2┃ &8⋅ &fРазработка&7: &a&lTemaFlux&r &7(vk.com/artemvka)"
    - "&r &2&m┖                                       &r"
    reload: "&a[✔]&8 › &fКонфигурация плагина &a&lуспешно&f перезагружена."
    sell: "&a&l[!]&8 › &fВы успешно выставили предмет на аукцион за &2{price}&a изумрудов."
    buy: "&a&l[!]&8 › &fВы успешно купили предмет на аукционе за &2{price}&a изумрудов."
  errors:
    noArgs: "&c[⚠]&8 › &fИспользуйте: &4/{cmd} help &fдля вывода помощи"
    onlyPlayer: "&c[⚠]&8 › &fДанная команда &c&lразрешена&f только для игроков!"
    noPerm: "&c[⚠]&8 › &fУ вас &c&lнедостаточно &fправ на использование!"
    buy:
      notEnough: "&c[⚠]&8 › &fУ вас &c&lнедостаточно &fизумрудов для покупки!"
    subCommands:
      sell:
        noArg: "&cВы забыли указать цену!"
        notNumber: "&cВы ввели не верную цену!"
        notEnough: "&cУ вас не достаточно предметов!"
        min:
          price: "&cМинимальная цена: &4{price} изумруд(а,ов)&c, для установки на аукцион."
          item: "&cВы не можете продать меньше 1 предмета."
        max:
          price: "&cМаксимальная цена: &4{price} изумруд(а,ов)&c, для установки на аукцион."
          item: "&cВы не можете продать больше 64 предмета."
        place: "&cВы уже выставили макс. кол-во предметов на аукцион."
        item:
          air: "&cВы не можете продать воздух! Возьмите предмет для продажи."
          blocked: "&cДанный предмет не разрешен для продажи! Попробуйте продать другой предмет."
      unknown: "&cНеизвестная суб-команда!"